### ISSUE TITLE
The reporting data you are trying to fetch has too many rows

### ISSUE THREAD

**Issue by chaitu1124** [mara/facebook-ads-performance-downloader#13]
Hi, 

Getting following error when I tried to run "facebook-ads-performance-downloder". I know this error related to facebook but we can improve the program by using asynchronously. 

 Response:
    {
      "error": {
        "message": "Invalid parameter",
        "type": "OAuthException",
        "code": 100,
        "error_subcode": 1487534,
        "is_transient": false,
        "error_user_title": "Too many rows",
        "error_user_msg": "The reporting data you are trying to fetch has too many rows. Please use asynchronous query or restrict amount of ad IDs or time ranges to fetch the data.",
        "fbtrace_id": ""
      }
    }

Thanks,

**Comment by martin-loetzsch** [comment]
We can't replicate this. If you want to submit a PR, we'd be very happy to incorporate it
