### ISSUE TITLE
Update facebook-python-ads-sdk to 2.10

### ISSUE THREAD

**Issue by Tafkas** [mara/facebook-ads-performance-downloader#3]
Current release of the facebook-python-ads-sdk is [2.10](https://github.com/facebook/facebook-python-ads-sdk/releases). Also current Facebook Marketing API version is [2.10](https://developers.facebook.com/docs/marketing-api/reference/v2.10).

**Comment by morganhoward** [comment]
hi.  I'd like to work on this.

**Comment by jacopofar** [comment]
Merged, thanks @morganhoward
